### ISSUE TITLE
EPIC: have nzshm-model support all NSHM logic tree use cases

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-model#19]
## Context
The NZSHM model is defined by logic trees - as is the convention in seismic hazard calculation. Traditionally a complete logic tree specification would be provided to the PSHA engine (openquake) for processing,  and the output is a complete hazard model. 

For various reasons*, NZ NSHM 22 changes this slightly. We subdivide the full logic tree into sub-sections and pass each of these to the PSHA engine as small, complete PSHA jobs. (presently 49 sub-tasks for the complete model), Now we take the realisations from each sub-task and aggregate these (ref toshi-hazard-post) to produce the complete hazard model. This post-processing step requires:
 - all the sub-task hazard realisations
 - the full logic tree, including branch weights (and soon - the  rate-scaling arguments)

## Details
We want **nzshm-model** to represent the various uses of the logic tree, to distinguish between the 'complete logic tree' and the sub-task logic-trees, so that all this logic is expressed in one convenient place.

This will allow both automated and manual processing to take advantage of the same feature set.

**Key model features then must include:**
 - [x] subdivide the logic tree into desired component parts (including scaling switch)
   - [x] filtering component paths so that user has flexibility for testing etc
   - [x] use the above to build a smaller model from a larger one ????
   - [x] each part must be easily identifiable and traceable to the the ' logic tree' aka the model (WIP)
         #15 
 - [x] mapping unique input ids (e.g. toshi_ids) to unique logic tree paths (WIP)
 - [x] fetching and organising openquake sources on disk (for oq job setup)
       #16 
 - [x] writing openquake source_model.xml (for oq job setup)
       #17 

**Also support:**
 - [x] option to configure new SLTs with individual sources (no more combo BG/FG)
 - [ ] decomposed GMM
 - [ ] scaling as per NSHM_v1.0.4 (for backwards compatibility and 'sanity checking')
 - [ ] agree FUTURE NRML support for post-scaling (w GEM) ,,,
 - [ ] produce breaking NRML for complete tree, because sources are missed and weights don't sum.
 - [x] For now "complete LTs" will use flattened approach, but in future may use Extended NRML for better oq performance?

**Comment by chrisdicaprio** [comment]
with OQ v3.21 capable of processing entire NZHSM logic tree, we should add support for `ExtendedModel` used to do so
